"""Generates Wáay's Material 3 fallback colour scheme (Android 8–11, no dynamic colour; ADR-016).

Material Color Utilities' TonalSpot scheme (the Material Theme Builder algorithm) from the brand
seed, for every role `lightColorScheme`/`darkColorScheme` take in Material 3 1.4.0.

Usage:
    uvx --from materialyoucolor==3.0.4 python scripts/generate-android-fallback-colors.py \
        > androidApp/src/main/kotlin/dev/epool/waay/android/ui/theme/Color.kt
"""

import importlib.metadata
import re

from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
from materialyoucolor.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

SEED = 0xFF4527A0  # the iOS accent colour and the app icon's violet
ROLES = """
primary onPrimary primaryContainer onPrimaryContainer inversePrimary
secondary onSecondary secondaryContainer onSecondaryContainer
tertiary onTertiary tertiaryContainer onTertiaryContainer
background onBackground surface onSurface surfaceVariant onSurfaceVariant surfaceTint
inverseSurface inverseOnSurface error onError errorContainer onErrorContainer
outline outlineVariant scrim
surfaceBright surfaceContainer surfaceContainerHigh surfaceContainerHighest
surfaceContainerLow surfaceContainerLowest surfaceDim
primaryFixed primaryFixedDim onPrimaryFixed onPrimaryFixedVariant
secondaryFixed secondaryFixedDim onSecondaryFixed onSecondaryFixedVariant
tertiaryFixed tertiaryFixedDim onTertiaryFixed onTertiaryFixedVariant
""".split()

def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def role(name: str):
    for candidate in (name, snake(name)):
        if hasattr(MaterialDynamicColors, candidate):
            return getattr(MaterialDynamicColors, candidate)
    raise SystemExit(f"Unknown role: {name}")


def scheme_entries(dark: bool) -> list[str]:
    scheme = SchemeTonalSpot(Hct.from_int(SEED), dark, 0.0)
    return [f"        {name} = Color(0xFF{role(name).get_argb(scheme) & 0xFFFFFF:06X})," for name in ROLES]


version = importlib.metadata.version("materialyoucolor")
print(f"""package dev.epool.waay.android.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// GENERATED by scripts/generate-android-fallback-colors.py with materialyoucolor {version}
// (Material Color Utilities, TonalSpot) from seed #{SEED & 0xFFFFFF:06X}. Do not edit by hand.
// Used where dynamic colour is unavailable (Android 8–11); see ADR-016.

/** Wáay's Material 3 light scheme for devices without dynamic colour. */
internal val WaayLightColorScheme =
    lightColorScheme(
{chr(10).join(scheme_entries(dark=False))}
    )

/** Wáay's Material 3 dark scheme for devices without dynamic colour. */
internal val WaayDarkColorScheme =
    darkColorScheme(
{chr(10).join(scheme_entries(dark=True))}
    )""")
